//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPDCtrlX.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MPDCtrlX.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} albums に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AlbumPage_SubTitle_AlbumCount {
            get {
                return ResourceManager.GetString("AlbumPage_SubTitle_AlbumCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} artists に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArtistPage_SubTitle_ArtistCount {
            get {
                return ResourceManager.GetString("ArtistPage_SubTitle_ArtistCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangePasswordDialog_ChangePassword {
            get {
                return ResourceManager.GetString("ChangePasswordDialog_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangePasswordDialog_CurrentPassword {
            get {
                return ResourceManager.GetString("ChangePasswordDialog_CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Password did not match. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangePasswordDialog_CurrentPasswordMismatch {
            get {
                return ResourceManager.GetString("ChangePasswordDialog_CurrentPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangePasswordDialog_NewPassword {
            get {
                return ResourceManager.GetString("ChangePasswordDialog_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password Updated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangePasswordDialog_PasswordUpdated {
            get {
                return ResourceManager.GetString("ChangePasswordDialog_PasswordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_Connected {
            get {
                return ResourceManager.GetString("ConnectionStatus_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection terminated. (ConnectFail_Timeout) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_ConnectFail_Timeout {
            get {
                return ResourceManager.GetString("ConnectionStatus_ConnectFail_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connecting... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_Connecting {
            get {
                return ResourceManager.GetString("ConnectionStatus_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionStatus_ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to connect to specified MPD server. Please check your connection settings or MPD server. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_ConnectionErrorDetails {
            get {
                return ResourceManager.GetString("ConnectionStatus_ConnectionErrorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection has been terminated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_Disconnected {
            get {
                return ResourceManager.GetString("ConnectionStatus_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection terminated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_DisconnectedByHost {
            get {
                return ResourceManager.GetString("ConnectionStatus_DisconnectedByHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection terminated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_DisconnectedByUser {
            get {
                return ResourceManager.GetString("ConnectionStatus_DisconnectedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disconnecting... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_Disconnecting {
            get {
                return ResourceManager.GetString("ConnectionStatus_Disconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection terminated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_NeverConnected {
            get {
                return ResourceManager.GetString("ConnectionStatus_NeverConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection terminated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_SendFail_NotConnected {
            get {
                return ResourceManager.GetString("ConnectionStatus_SendFail_NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection terminated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStatus_SendFail_Timeout {
            get {
                return ResourceManager.GetString("ConnectionStatus_SendFail_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_CancelClose {
            get {
                return ResourceManager.GetString("Dialog_CancelClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comfirmation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_Comfirmation {
            get {
                return ResourceManager.GetString("Dialog_Comfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create new playlist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_CreateNewPlaylist {
            get {
                return ResourceManager.GetString("Dialog_CreateNewPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_Information {
            get {
                return ResourceManager.GetString("Dialog_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_Input {
            get {
                return ResourceManager.GetString("Dialog_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_Ok {
            get {
                return ResourceManager.GetString("Dialog_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Playlist name already exists. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_PlaylistNameAlreadyExists {
            get {
                return ResourceManager.GetString("Dialog_PlaylistNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Playlist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_PlaylistSelect_NewPlaylistName {
            get {
                return ResourceManager.GetString("Dialog_PlaylistSelect_NewPlaylistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Selected to に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_PlaylistSelect_SaveSelectedTo {
            get {
                return ResourceManager.GetString("Dialog_PlaylistSelect_SaveSelectedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Playlist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_PlaylistSelect_SelectPlaylist {
            get {
                return ResourceManager.GetString("Dialog_PlaylistSelect_SelectPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove selected playlist? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_RemovePlaylistQ {
            get {
                return ResourceManager.GetString("Dialog_RemovePlaylistQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter a new playlist name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_TextBox_Watermark_EnterNewPlaylistName {
            get {
                return ResourceManager.GetString("Dialog_TextBox_Watermark_EnterNewPlaylistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter a new playlist name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_TextBox_Watermark_EnterNewRenamedPlaylistName {
            get {
                return ResourceManager.GetString("Dialog_TextBox_Watermark_EnterNewRenamedPlaylistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New playlist name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_Title_NewPlaylistName {
            get {
                return ResourceManager.GetString("Dialog_Title_NewPlaylistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select playlist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_Title_SelectPlaylist {
            get {
                return ResourceManager.GetString("Dialog_Title_SelectPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FilesListviewColumnHeader_FileName {
            get {
                return ResourceManager.GetString("FilesListviewColumnHeader_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FilesListviewColumnHeader_FilePath {
            get {
                return ResourceManager.GetString("FilesListviewColumnHeader_FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FilesPage_SubTitle_FileCount {
            get {
                return ResourceManager.GetString("FilesPage_SubTitle_FileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear filter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FilterClear {
            get {
                return ResourceManager.GetString("FilterClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add to playlist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FlyoutMenu_AddToPlaylist {
            get {
                return ResourceManager.GetString("FlyoutMenu_AddToPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FlyoutMenu_Clear {
            get {
                return ResourceManager.GetString("FlyoutMenu_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column visibility に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FlyoutMenu_ColumnVisibility {
            get {
                return ResourceManager.GetString("FlyoutMenu_ColumnVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Go to album page に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FlyoutMenu_GoToAlbumPage {
            get {
                return ResourceManager.GetString("FlyoutMenu_GoToAlbumPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Go to artist page に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FlyoutMenu_GoToArtistPage {
            get {
                return ResourceManager.GetString("FlyoutMenu_GoToArtistPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scroll to current track に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FlyoutMenu_ScrollIntoNowPlaying {
            get {
                return ResourceManager.GetString("FlyoutMenu_ScrollIntoNowPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Host に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Connection Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Init_NewConnectionSetting {
            get {
                return ResourceManager.GetString("Init_NewConnectionSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InitialSetupWindow_Connect {
            get {
                return ResourceManager.GetString("InitialSetupWindow_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MPDCtrlX requires MPD (Music Player Daemon) to be installed (localy or remotely) and running preferably as a service (aka daemon). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InitialSetupWindow_Description {
            get {
                return ResourceManager.GetString("InitialSetupWindow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remember this に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InitialSetupWindow_RememberThis {
            get {
                return ResourceManager.GetString("InitialSetupWindow_RememberThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initial configuration に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InitialSetupWindow_Subtitle {
            get {
                return ResourceManager.GetString("InitialSetupWindow_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default is 6600 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InitialSetupWindow_Watermark_DefaultIs6600 {
            get {
                return ResourceManager.GetString("InitialSetupWindow_Watermark_DefaultIs6600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP address or PC/Server name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InitialSetupWindow_Watermark_IPAddressOrServerName {
            get {
                return ResourceManager.GetString("InitialSetupWindow_Watermark_IPAddressOrServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Optional unless configured otherwise に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InitialSetupWindow_Watermark_OptionalUnlessConfiguredOtherwise {
            get {
                return ResourceManager.GetString("InitialSetupWindow_Watermark_OptionalUnlessConfiguredOtherwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   License に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copyright (c) 2025 torum
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice and this permiss [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LicenseText {
            get {
                return ResourceManager.GetString("LicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The MIT License に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LicenseTitle {
            get {
                return ResourceManager.GetString("LicenseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Album に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListviewColumnHeader_Album {
            get {
                return ResourceManager.GetString("ListviewColumnHeader_Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Artist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListviewColumnHeader_Artist {
            get {
                return ResourceManager.GetString("ListviewColumnHeader_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disc に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListviewColumnHeader_Disc {
            get {
                return ResourceManager.GetString("ListviewColumnHeader_Disc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Genre に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListviewColumnHeader_Genre {
            get {
                return ResourceManager.GetString("ListviewColumnHeader_Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last Modified に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListviewColumnHeader_LastModified {
            get {
                return ResourceManager.GetString("ListviewColumnHeader_LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListviewColumnHeader_Position {
            get {
                return ResourceManager.GetString("ListviewColumnHeader_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListviewColumnHeader_Time {
            get {
                return ResourceManager.GetString("ListviewColumnHeader_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListviewColumnHeader_Title {
            get {
                return ResourceManager.GetString("ListviewColumnHeader_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Track に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListviewColumnHeader_Track {
            get {
                return ResourceManager.GetString("ListviewColumnHeader_Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add to playlist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListviewItemContextMenu_AddToPlaylist {
            get {
                return ResourceManager.GetString("ListviewItemContextMenu_AddToPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add to queue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListviewItemContextMenu_AddToQueue {
            get {
                return ResourceManager.GetString("ListviewItemContextMenu_AddToQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Go to album page に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListviewItemContextMenu_GoToAlbumPage {
            get {
                return ResourceManager.GetString("ListviewItemContextMenu_GoToAlbumPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Go to artist page に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListviewItemContextMenu_GoToArtistPage {
            get {
                return ResourceManager.GetString("ListviewItemContextMenu_GoToArtistPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move down に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListviewItemContextMenu_MoveDown {
            get {
                return ResourceManager.GetString("ListviewItemContextMenu_MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move up に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListViewItemContextMenu_MoveUp {
            get {
                return ResourceManager.GetString("ListViewItemContextMenu_MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListViewItemContextMenu_Play {
            get {
                return ResourceManager.GetString("ListViewItemContextMenu_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListviewItemContextMenu_Remove {
            get {
                return ResourceManager.GetString("ListviewItemContextMenu_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add to queue (Enter) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LocalfileItemContextMenu_AddToQueue {
            get {
                return ResourceManager.GetString("LocalfileItemContextMenu_AddToQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LocalfileListviewTabitemHeader_LocalFiles {
            get {
                return ResourceManager.GetString("LocalfileListviewTabitemHeader_LocalFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Albums に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuTreeItem_Albums {
            get {
                return ResourceManager.GetString("MenuTreeItem_Albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Artists に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuTreeItem_Artists {
            get {
                return ResourceManager.GetString("MenuTreeItem_Artists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuTreeItem_Files {
            get {
                return ResourceManager.GetString("MenuTreeItem_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Library に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuTreeItem_Library {
            get {
                return ResourceManager.GetString("MenuTreeItem_Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Playlists に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuTreeItem_Playlists {
            get {
                return ResourceManager.GetString("MenuTreeItem_Playlists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Queue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuTreeItem_Queue {
            get {
                return ResourceManager.GetString("MenuTreeItem_Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuTreeItem_Search {
            get {
                return ResourceManager.GetString("MenuTreeItem_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MPD Command Response に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MPD_CommandResponse {
            get {
                return ResourceManager.GetString("MPD_CommandResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MPD Response に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MPD_IdleResponse {
            get {
                return ResourceManager.GetString("MPD_IdleResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status Notification に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MPD_StatusError {
            get {
                return ResourceManager.GetString("MPD_StatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PageMenu_Filter {
            get {
                return ResourceManager.GetString("PageMenu_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PageMenu_Find {
            get {
                return ResourceManager.GetString("PageMenu_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   More に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PageMenu_More {
            get {
                return ResourceManager.GetString("PageMenu_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play all に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PageMenu_PlayAll {
            get {
                return ResourceManager.GetString("PageMenu_PlayAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Queue all に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PageMenu_QueueAll {
            get {
                return ResourceManager.GetString("PageMenu_QueueAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reverse order に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PageMenu_ReverseSort {
            get {
                return ResourceManager.GetString("PageMenu_ReverseSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PageMenu_Search {
            get {
                return ResourceManager.GetString("PageMenu_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sort and reorder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PageMenu_SortAndReorder {
            get {
                return ResourceManager.GetString("PageMenu_SortAndReorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back (Ctrl+B/Ctrl+Left/MediaKey) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Playback_BackButton {
            get {
                return ResourceManager.GetString("Playback_BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next (Ctrl+N/Ctrl+Right/MediaKey) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Playback_NextButton {
            get {
                return ResourceManager.GetString("Playback_NextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play/Pause (Ctrl+Space/Ctrl+P/MediaKeys) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Playback_PlayPauseButton {
            get {
                return ResourceManager.GetString("Playback_PlayPauseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seek に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Playback_SliderSeek {
            get {
                return ResourceManager.GetString("Playback_SliderSeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Volume に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Playback_SliderVolume {
            get {
                return ResourceManager.GetString("Playback_SliderVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consume に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaybackOptions_Consume {
            get {
                return ResourceManager.GetString("PlaybackOptions_Consume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Repeat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaybackOptions_Repeat {
            get {
                return ResourceManager.GetString("PlaybackOptions_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shuffle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaybackOptions_Shuffle {
            get {
                return ResourceManager.GetString("PlaybackOptions_Shuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Single に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaybackOptions_Single {
            get {
                return ResourceManager.GetString("PlaybackOptions_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear Queue and Load に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaylistItemContextMenu_ClearAndLoad {
            get {
                return ResourceManager.GetString("PlaylistItemContextMenu_ClearAndLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load (Enter) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaylistItemContextMenu_Load {
            get {
                return ResourceManager.GetString("PlaylistItemContextMenu_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaylistItemContextMenu_Remove {
            get {
                return ResourceManager.GetString("PlaylistItemContextMenu_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaylistItemContextMenu_Rename {
            get {
                return ResourceManager.GetString("PlaylistItemContextMenu_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaylistItemMenu_Clear {
            get {
                return ResourceManager.GetString("PlaylistItemMenu_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaylistItemMenu_Remove {
            get {
                return ResourceManager.GetString("PlaylistItemMenu_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaylistItemMenu_Rename {
            get {
                return ResourceManager.GetString("PlaylistItemMenu_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Playlists に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaylistListviewTabitemHeader_Playlists {
            get {
                return ResourceManager.GetString("PlaylistListviewTabitemHeader_Playlists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} songs に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaylistPage_SubTitle_SongCount {
            get {
                return ResourceManager.GetString("PlaylistPage_SubTitle_SongCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Playlists に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaylistsListviewColumnHeader_Playlists {
            get {
                return ResourceManager.GetString("PlaylistsListviewColumnHeader_Playlists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaylistSongsContextMenu_Clear {
            get {
                return ResourceManager.GetString("PlaylistSongsContextMenu_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Playlist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaylistSongsContextMenu_Playlist {
            get {
                return ResourceManager.GetString("PlaylistSongsContextMenu_Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove From Playlist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaylistSongsContextMenu_Remove {
            get {
                return ResourceManager.GetString("PlaylistSongsContextMenu_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   App Privacy Policy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MPDCtrl allows you to access your music player via specified IP address with optional user credentials. None of the data is transmitted anywhere besides your specified music player and your settings are stored on your device only. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrivacyPolicyText {
            get {
                return ResourceManager.GetString("PrivacyPolicyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Profile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Profile_NewProfile {
            get {
                return ResourceManager.GetString("Profile_NewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profiles に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} songs に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueuePage_SubTitle_SongCount {
            get {
                return ResourceManager.GetString("QueuePage_SubTitle_SongCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saved Profiles に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SavedProfiles {
            get {
                return ResourceManager.GetString("SavedProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contains に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Search_Shiki_Contains {
            get {
                return ResourceManager.GetString("Search_Shiki_Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Equals に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Search_Shiki_Equals {
            get {
                return ResourceManager.GetString("Search_Shiki_Equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search (Ctrl+F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Search_ToolTip {
            get {
                return ResourceManager.GetString("Search_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Any に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchOption_Any {
            get {
                return ResourceManager.GetString("SearchOption_Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchPage_SubTitle_ResultCount {
            get {
                return ResourceManager.GetString("SearchPage_SubTitle_ResultCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid address format. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ErrorHostInvalidAddressFormat {
            get {
                return ResourceManager.GetString("Settings_ErrorHostInvalidAddressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Host address is required. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ErrorHostMustBeSpecified {
            get {
                return ResourceManager.GetString("Settings_ErrorHostMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid port number. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ErrorInvalidPortNaN {
            get {
                return ResourceManager.GetString("Settings_ErrorInvalidPortNaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port number is required. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ErrorPortMustBeSpecified {
            get {
                return ResourceManager.GetString("Settings_ErrorPortMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto scroll to current song. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Opts_AutoScrollToNowPlaying {
            get {
                return ResourceManager.GetString("Settings_Opts_AutoScrollToNowPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable AlbumArt. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Opts_EnableAlbumArt {
            get {
                return ResourceManager.GetString("Settings_Opts_EnableAlbumArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Music Player Daemon に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Opts_MPD {
            get {
                return ResourceManager.GetString("Settings_Opts_MPD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Opts_MPD_Description {
            get {
                return ResourceManager.GetString("Settings_Opts_MPD_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reconnect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Opts_MPD_Reconnect {
            get {
                return ResourceManager.GetString("Settings_Opts_MPD_Reconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remember this に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Opts_MPD_RememberThis {
            get {
                return ResourceManager.GetString("Settings_Opts_MPD_RememberThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MPD Database に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Opts_MPDDatabase {
            get {
                return ResourceManager.GetString("Settings_Opts_MPDDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Opts_Options {
            get {
                return ResourceManager.GetString("Settings_Opts_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A few preferences に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Opts_Options_Description {
            get {
                return ResourceManager.GetString("Settings_Opts_Options_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save log file (MPDCtrl__errors.txt) to desktop when an unexpected error occured. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Opts_SaveLog {
            get {
                return ResourceManager.GetString("Settings_Opts_SaveLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable debug widow. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Opts_ShowDebugWidow {
            get {
                return ResourceManager.GetString("Settings_Opts_ShowDebugWidow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Themes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Opts_Themes {
            get {
                return ResourceManager.GetString("Settings_Opts_Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dark に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Opts_Themes_Dark {
            get {
                return ResourceManager.GetString("Settings_Opts_Themes_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change the current app theme に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Opts_Themes_Description {
            get {
                return ResourceManager.GetString("Settings_Opts_Themes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Opts_Themes_Light {
            get {
                return ResourceManager.GetString("Settings_Opts_Themes_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Opts_Themes_System {
            get {
                return ResourceManager.GetString("Settings_Opts_Themes_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update MPD database on startup. (It may take a while to update) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Opts_UpdateDatabaseOnStartup {
            get {
                return ResourceManager.GetString("Settings_Opts_UpdateDatabaseOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use &quot;readpicture&quot; command instead of &quot;albumart&quot;. (applicable when MPD protocol version is 0.22.0 or up) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Opts_UseReadPicture {
            get {
                return ResourceManager.GetString("Settings_Opts_UseReadPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_PageTitle {
            get {
                return ResourceManager.GetString("Settings_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profile deleted に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ProfileDeleted {
            get {
                return ResourceManager.GetString("Settings_ProfileDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profile saved. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ProfileSaved {
            get {
                return ResourceManager.GetString("Settings_ProfileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profile updated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ProfileUpdated {
            get {
                return ResourceManager.GetString("Settings_ProfileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Project info に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ProjectPage {
            get {
                return ResourceManager.GetString("Settings_ProjectPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This project is hosted at GitHub as a open source project. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ProjectPage_Description {
            get {
                return ResourceManager.GetString("Settings_ProjectPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings (Ctrl+S) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ToolTip {
            get {
                return ResourceManager.GetString("Settings_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unlock and change password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_UnlockAndChangePassword {
            get {
                return ResourceManager.GetString("Settings_UnlockAndChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (not used) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SongFilesItemContextMenu_Add {
            get {
                return ResourceManager.GetString("SongFilesItemContextMenu_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SongFilesListviewColumnHeader_File {
            get {
                return ResourceManager.GetString("SongFilesListviewColumnHeader_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SongFilesListviewColumnHeader_Path {
            get {
                return ResourceManager.GetString("SongFilesListviewColumnHeader_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add to Queue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SongsItemContextMenu_Add {
            get {
                return ResourceManager.GetString("SongsItemContextMenu_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The MPD protocol version {0} is old. Some of the functionalities may not work properly. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StatusBarMsg_MPDVersionIsOld {
            get {
                return ResourceManager.GetString("StatusBarMsg_MPDVersionIsOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Updating database... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StatusMsg_UpdatingDb {
            get {
                return ResourceManager.GetString("StatusMsg_UpdatingDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Website に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
