//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPDCtrlX.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MPDCtrlX.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} albums.
        /// </summary>
        public static string AlbumPage_SubTitle_AlbumCount {
            get {
                return ResourceManager.GetString("AlbumPage_SubTitle_AlbumCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} artists.
        /// </summary>
        public static string ArtistPage_SubTitle_ArtistCount {
            get {
                return ResourceManager.GetString("ArtistPage_SubTitle_ArtistCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePasswordDialog_ChangePassword {
            get {
                return ResourceManager.GetString("ChangePasswordDialog_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string ChangePasswordDialog_CurrentPassword {
            get {
                return ResourceManager.GetString("ChangePasswordDialog_CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password did not match..
        /// </summary>
        public static string ChangePasswordDialog_CurrentPasswordMismatch {
            get {
                return ResourceManager.GetString("ChangePasswordDialog_CurrentPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string ChangePasswordDialog_NewPassword {
            get {
                return ResourceManager.GetString("ChangePasswordDialog_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Updated..
        /// </summary>
        public static string ChangePasswordDialog_PasswordUpdated {
            get {
                return ResourceManager.GetString("ChangePasswordDialog_PasswordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected..
        /// </summary>
        public static string ConnectionStatus_Connected {
            get {
                return ResourceManager.GetString("ConnectionStatus_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection terminated. (ConnectFail_Timeout).
        /// </summary>
        public static string ConnectionStatus_ConnectFail_Timeout {
            get {
                return ResourceManager.GetString("ConnectionStatus_ConnectFail_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        public static string ConnectionStatus_Connecting {
            get {
                return ResourceManager.GetString("ConnectionStatus_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Error.
        /// </summary>
        public static string ConnectionStatus_ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionStatus_ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to specified MPD server. Please check your connection settings or MPD server..
        /// </summary>
        public static string ConnectionStatus_ConnectionErrorDetails {
            get {
                return ResourceManager.GetString("ConnectionStatus_ConnectionErrorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection has been terminated..
        /// </summary>
        public static string ConnectionStatus_Disconnected {
            get {
                return ResourceManager.GetString("ConnectionStatus_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection terminated..
        /// </summary>
        public static string ConnectionStatus_DisconnectedByHost {
            get {
                return ResourceManager.GetString("ConnectionStatus_DisconnectedByHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection terminated..
        /// </summary>
        public static string ConnectionStatus_DisconnectedByUser {
            get {
                return ResourceManager.GetString("ConnectionStatus_DisconnectedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnecting....
        /// </summary>
        public static string ConnectionStatus_Disconnecting {
            get {
                return ResourceManager.GetString("ConnectionStatus_Disconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection terminated..
        /// </summary>
        public static string ConnectionStatus_NeverConnected {
            get {
                return ResourceManager.GetString("ConnectionStatus_NeverConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection terminated..
        /// </summary>
        public static string ConnectionStatus_SendFail_NotConnected {
            get {
                return ResourceManager.GetString("ConnectionStatus_SendFail_NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection terminated..
        /// </summary>
        public static string ConnectionStatus_SendFail_Timeout {
            get {
                return ResourceManager.GetString("ConnectionStatus_SendFail_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Dialog_CancelClose {
            get {
                return ResourceManager.GetString("Dialog_CancelClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comfirmation.
        /// </summary>
        public static string Dialog_Comfirmation {
            get {
                return ResourceManager.GetString("Dialog_Comfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new playlist.
        /// </summary>
        public static string Dialog_CreateNewPlaylist {
            get {
                return ResourceManager.GetString("Dialog_CreateNewPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Dialog_Information {
            get {
                return ResourceManager.GetString("Dialog_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Dialog_Input {
            get {
                return ResourceManager.GetString("Dialog_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Dialog_Ok {
            get {
                return ResourceManager.GetString("Dialog_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist name already exists..
        /// </summary>
        public static string Dialog_PlaylistNameAlreadyExists {
            get {
                return ResourceManager.GetString("Dialog_PlaylistNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Playlist.
        /// </summary>
        public static string Dialog_PlaylistSelect_NewPlaylistName {
            get {
                return ResourceManager.GetString("Dialog_PlaylistSelect_NewPlaylistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Selected to.
        /// </summary>
        public static string Dialog_PlaylistSelect_SaveSelectedTo {
            get {
                return ResourceManager.GetString("Dialog_PlaylistSelect_SaveSelectedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Playlist.
        /// </summary>
        public static string Dialog_PlaylistSelect_SelectPlaylist {
            get {
                return ResourceManager.GetString("Dialog_PlaylistSelect_SelectPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected playlist?.
        /// </summary>
        public static string Dialog_RemovePlaylistQ {
            get {
                return ResourceManager.GetString("Dialog_RemovePlaylistQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a new playlist name.
        /// </summary>
        public static string Dialog_TextBox_Watermark_EnterNewPlaylistName {
            get {
                return ResourceManager.GetString("Dialog_TextBox_Watermark_EnterNewPlaylistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a new playlist name.
        /// </summary>
        public static string Dialog_TextBox_Watermark_EnterNewRenamedPlaylistName {
            get {
                return ResourceManager.GetString("Dialog_TextBox_Watermark_EnterNewRenamedPlaylistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New playlist name.
        /// </summary>
        public static string Dialog_Title_NewPlaylistName {
            get {
                return ResourceManager.GetString("Dialog_Title_NewPlaylistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select playlist.
        /// </summary>
        public static string Dialog_Title_SelectPlaylist {
            get {
                return ResourceManager.GetString("Dialog_Title_SelectPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string FilesListviewColumnHeader_FileName {
            get {
                return ResourceManager.GetString("FilesListviewColumnHeader_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path.
        /// </summary>
        public static string FilesListviewColumnHeader_FilePath {
            get {
                return ResourceManager.GetString("FilesListviewColumnHeader_FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files.
        /// </summary>
        public static string FilesPage_SubTitle_FileCount {
            get {
                return ResourceManager.GetString("FilesPage_SubTitle_FileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear filter.
        /// </summary>
        public static string FilterClear {
            get {
                return ResourceManager.GetString("FilterClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to playlist.
        /// </summary>
        public static string FlyoutMenu_AddToPlaylist {
            get {
                return ResourceManager.GetString("FlyoutMenu_AddToPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string FlyoutMenu_Clear {
            get {
                return ResourceManager.GetString("FlyoutMenu_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column visibility.
        /// </summary>
        public static string FlyoutMenu_ColumnVisibility {
            get {
                return ResourceManager.GetString("FlyoutMenu_ColumnVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to album page.
        /// </summary>
        public static string FlyoutMenu_GoToAlbumPage {
            get {
                return ResourceManager.GetString("FlyoutMenu_GoToAlbumPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to artist page.
        /// </summary>
        public static string FlyoutMenu_GoToArtistPage {
            get {
                return ResourceManager.GetString("FlyoutMenu_GoToArtistPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll to current track.
        /// </summary>
        public static string FlyoutMenu_ScrollIntoNowPlaying {
            get {
                return ResourceManager.GetString("FlyoutMenu_ScrollIntoNowPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Connection Setting.
        /// </summary>
        public static string Init_NewConnectionSetting {
            get {
                return ResourceManager.GetString("Init_NewConnectionSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string InitialSetupWindow_Connect {
            get {
                return ResourceManager.GetString("InitialSetupWindow_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPDCtrlX requires MPD (Music Player Daemon) to be installed (localy or remotely) and running preferably as a service (aka daemon)..
        /// </summary>
        public static string InitialSetupWindow_Description {
            get {
                return ResourceManager.GetString("InitialSetupWindow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember this.
        /// </summary>
        public static string InitialSetupWindow_RememberThis {
            get {
                return ResourceManager.GetString("InitialSetupWindow_RememberThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial configuration.
        /// </summary>
        public static string InitialSetupWindow_Subtitle {
            get {
                return ResourceManager.GetString("InitialSetupWindow_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default is 6600.
        /// </summary>
        public static string InitialSetupWindow_Watermark_DefaultIs6600 {
            get {
                return ResourceManager.GetString("InitialSetupWindow_Watermark_DefaultIs6600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address or PC/Server name.
        /// </summary>
        public static string InitialSetupWindow_Watermark_IPAddressOrServerName {
            get {
                return ResourceManager.GetString("InitialSetupWindow_Watermark_IPAddressOrServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional unless configured otherwise.
        /// </summary>
        public static string InitialSetupWindow_Watermark_OptionalUnlessConfiguredOtherwise {
            get {
                return ResourceManager.GetString("InitialSetupWindow_Watermark_OptionalUnlessConfiguredOtherwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2018~ torum
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice and this permis [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LicenseText {
            get {
                return ResourceManager.GetString("LicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MIT License.
        /// </summary>
        public static string LicenseTitle {
            get {
                return ResourceManager.GetString("LicenseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string ListviewColumnHeader_Album {
            get {
                return ResourceManager.GetString("ListviewColumnHeader_Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string ListviewColumnHeader_Artist {
            get {
                return ResourceManager.GetString("ListviewColumnHeader_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disc.
        /// </summary>
        public static string ListviewColumnHeader_Disc {
            get {
                return ResourceManager.GetString("ListviewColumnHeader_Disc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string ListviewColumnHeader_Genre {
            get {
                return ResourceManager.GetString("ListviewColumnHeader_Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified.
        /// </summary>
        public static string ListviewColumnHeader_LastModified {
            get {
                return ResourceManager.GetString("ListviewColumnHeader_LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string ListviewColumnHeader_Position {
            get {
                return ResourceManager.GetString("ListviewColumnHeader_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string ListviewColumnHeader_Time {
            get {
                return ResourceManager.GetString("ListviewColumnHeader_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string ListviewColumnHeader_Title {
            get {
                return ResourceManager.GetString("ListviewColumnHeader_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track.
        /// </summary>
        public static string ListviewColumnHeader_Track {
            get {
                return ResourceManager.GetString("ListviewColumnHeader_Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to playlist.
        /// </summary>
        public static string ListviewItemContextMenu_AddToPlaylist {
            get {
                return ResourceManager.GetString("ListviewItemContextMenu_AddToPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to queue.
        /// </summary>
        public static string ListviewItemContextMenu_AddToQueue {
            get {
                return ResourceManager.GetString("ListviewItemContextMenu_AddToQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy File Path.
        /// </summary>
        public static string ListviewItemContextMenu_CopyFilePath {
            get {
                return ResourceManager.GetString("ListviewItemContextMenu_CopyFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to album page.
        /// </summary>
        public static string ListviewItemContextMenu_GoToAlbumPage {
            get {
                return ResourceManager.GetString("ListviewItemContextMenu_GoToAlbumPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to artist page.
        /// </summary>
        public static string ListviewItemContextMenu_GoToArtistPage {
            get {
                return ResourceManager.GetString("ListviewItemContextMenu_GoToArtistPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        public static string ListviewItemContextMenu_MoveDown {
            get {
                return ResourceManager.GetString("ListviewItemContextMenu_MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        public static string ListViewItemContextMenu_MoveUp {
            get {
                return ResourceManager.GetString("ListViewItemContextMenu_MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string ListViewItemContextMenu_Play {
            get {
                return ResourceManager.GetString("ListViewItemContextMenu_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string ListviewItemContextMenu_Remove {
            get {
                return ResourceManager.GetString("ListviewItemContextMenu_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to queue (Enter).
        /// </summary>
        public static string LocalfileItemContextMenu_AddToQueue {
            get {
                return ResourceManager.GetString("LocalfileItemContextMenu_AddToQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Files.
        /// </summary>
        public static string LocalfileListviewTabitemHeader_LocalFiles {
            get {
                return ResourceManager.GetString("LocalfileListviewTabitemHeader_LocalFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albums.
        /// </summary>
        public static string MenuTreeItem_Albums {
            get {
                return ResourceManager.GetString("MenuTreeItem_Albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artists.
        /// </summary>
        public static string MenuTreeItem_Artists {
            get {
                return ResourceManager.GetString("MenuTreeItem_Artists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string MenuTreeItem_Files {
            get {
                return ResourceManager.GetString("MenuTreeItem_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string MenuTreeItem_Library {
            get {
                return ResourceManager.GetString("MenuTreeItem_Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        public static string MenuTreeItem_Playlists {
            get {
                return ResourceManager.GetString("MenuTreeItem_Playlists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        public static string MenuTreeItem_Queue {
            get {
                return ResourceManager.GetString("MenuTreeItem_Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string MenuTreeItem_Search {
            get {
                return ResourceManager.GetString("MenuTreeItem_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPD Command Response.
        /// </summary>
        public static string MPD_CommandResponse {
            get {
                return ResourceManager.GetString("MPD_CommandResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPD Response.
        /// </summary>
        public static string MPD_IdleResponse {
            get {
                return ResourceManager.GetString("MPD_IdleResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Notification.
        /// </summary>
        public static string MPD_StatusError {
            get {
                return ResourceManager.GetString("MPD_StatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string PageMenu_Filter {
            get {
                return ResourceManager.GetString("PageMenu_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string PageMenu_Find {
            get {
                return ResourceManager.GetString("PageMenu_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string PageMenu_More {
            get {
                return ResourceManager.GetString("PageMenu_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play all.
        /// </summary>
        public static string PageMenu_PlayAll {
            get {
                return ResourceManager.GetString("PageMenu_PlayAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference.
        /// </summary>
        public static string PageMenu_Preference {
            get {
                return ResourceManager.GetString("PageMenu_Preference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue all.
        /// </summary>
        public static string PageMenu_QueueAll {
            get {
                return ResourceManager.GetString("PageMenu_QueueAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse order.
        /// </summary>
        public static string PageMenu_ReverseSort {
            get {
                return ResourceManager.GetString("PageMenu_ReverseSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string PageMenu_Search {
            get {
                return ResourceManager.GetString("PageMenu_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort and reorder.
        /// </summary>
        public static string PageMenu_SortAndReorder {
            get {
                return ResourceManager.GetString("PageMenu_SortAndReorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back (Ctrl+B/Ctrl+Left/MediaKey).
        /// </summary>
        public static string Playback_BackButton {
            get {
                return ResourceManager.GetString("Playback_BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next (Ctrl+N/Ctrl+Right/MediaKey).
        /// </summary>
        public static string Playback_NextButton {
            get {
                return ResourceManager.GetString("Playback_NextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play/Pause (Ctrl+Space/Ctrl+P/MediaKeys).
        /// </summary>
        public static string Playback_PlayPauseButton {
            get {
                return ResourceManager.GetString("Playback_PlayPauseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seek.
        /// </summary>
        public static string Playback_SliderSeek {
            get {
                return ResourceManager.GetString("Playback_SliderSeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string Playback_SliderVolume {
            get {
                return ResourceManager.GetString("Playback_SliderVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consume.
        /// </summary>
        public static string PlaybackOptions_Consume {
            get {
                return ResourceManager.GetString("PlaybackOptions_Consume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        public static string PlaybackOptions_Repeat {
            get {
                return ResourceManager.GetString("PlaybackOptions_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle.
        /// </summary>
        public static string PlaybackOptions_Shuffle {
            get {
                return ResourceManager.GetString("PlaybackOptions_Shuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        public static string PlaybackOptions_Single {
            get {
                return ResourceManager.GetString("PlaybackOptions_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Queue and Load.
        /// </summary>
        public static string PlaylistItemContextMenu_ClearAndLoad {
            get {
                return ResourceManager.GetString("PlaylistItemContextMenu_ClearAndLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load (Enter).
        /// </summary>
        public static string PlaylistItemContextMenu_Load {
            get {
                return ResourceManager.GetString("PlaylistItemContextMenu_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string PlaylistItemContextMenu_Remove {
            get {
                return ResourceManager.GetString("PlaylistItemContextMenu_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string PlaylistItemContextMenu_Rename {
            get {
                return ResourceManager.GetString("PlaylistItemContextMenu_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string PlaylistItemMenu_Clear {
            get {
                return ResourceManager.GetString("PlaylistItemMenu_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string PlaylistItemMenu_Remove {
            get {
                return ResourceManager.GetString("PlaylistItemMenu_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string PlaylistItemMenu_Rename {
            get {
                return ResourceManager.GetString("PlaylistItemMenu_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Playlists.
        /// </summary>
        public static string PlaylistListviewTabitemHeader_Playlists {
            get {
                return ResourceManager.GetString("PlaylistListviewTabitemHeader_Playlists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} songs.
        /// </summary>
        public static string PlaylistPage_SubTitle_SongCount {
            get {
                return ResourceManager.GetString("PlaylistPage_SubTitle_SongCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        public static string PlaylistsListviewColumnHeader_Playlists {
            get {
                return ResourceManager.GetString("PlaylistsListviewColumnHeader_Playlists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string PlaylistSongsContextMenu_Clear {
            get {
                return ResourceManager.GetString("PlaylistSongsContextMenu_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist.
        /// </summary>
        public static string PlaylistSongsContextMenu_Playlist {
            get {
                return ResourceManager.GetString("PlaylistSongsContextMenu_Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove From Playlist.
        /// </summary>
        public static string PlaylistSongsContextMenu_Remove {
            get {
                return ResourceManager.GetString("PlaylistSongsContextMenu_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPDCtrlX allows you to access your music player via specified IP address with optional user credentials. None of the data is transmitted anywhere besides your specified music player and your settings are stored on your device only..
        /// </summary>
        public static string PrivacyPolicyText {
            get {
                return ResourceManager.GetString("PrivacyPolicyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Profile.
        /// </summary>
        public static string Profile_NewProfile {
            get {
                return ResourceManager.GetString("Profile_NewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        public static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} songs.
        /// </summary>
        public static string QueuePage_SubTitle_SongCount {
            get {
                return ResourceManager.GetString("QueuePage_SubTitle_SongCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Profiles.
        /// </summary>
        public static string SavedProfiles {
            get {
                return ResourceManager.GetString("SavedProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        public static string Search_Shiki_Contains {
            get {
                return ResourceManager.GetString("Search_Shiki_Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equals.
        /// </summary>
        public static string Search_Shiki_Equals {
            get {
                return ResourceManager.GetString("Search_Shiki_Equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search (Ctrl+F).
        /// </summary>
        public static string Search_ToolTip {
            get {
                return ResourceManager.GetString("Search_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        public static string SearchOption_Any {
            get {
                return ResourceManager.GetString("SearchOption_Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} result.
        /// </summary>
        public static string SearchPage_SubTitle_ResultCount {
            get {
                return ResourceManager.GetString("SearchPage_SubTitle_ResultCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid address format..
        /// </summary>
        public static string Settings_ErrorHostInvalidAddressFormat {
            get {
                return ResourceManager.GetString("Settings_ErrorHostInvalidAddressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host address is required..
        /// </summary>
        public static string Settings_ErrorHostMustBeSpecified {
            get {
                return ResourceManager.GetString("Settings_ErrorHostMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid port number..
        /// </summary>
        public static string Settings_ErrorInvalidPortNaN {
            get {
                return ResourceManager.GetString("Settings_ErrorInvalidPortNaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port number is required..
        /// </summary>
        public static string Settings_ErrorPortMustBeSpecified {
            get {
                return ResourceManager.GetString("Settings_ErrorPortMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto scroll to current song..
        /// </summary>
        public static string Settings_Opts_AutoScrollToNowPlaying {
            get {
                return ResourceManager.GetString("Settings_Opts_AutoScrollToNowPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable AlbumArt..
        /// </summary>
        public static string Settings_Opts_EnableAlbumArt {
            get {
                return ResourceManager.GetString("Settings_Opts_EnableAlbumArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Player Daemon.
        /// </summary>
        public static string Settings_Opts_MPD {
            get {
                return ResourceManager.GetString("Settings_Opts_MPD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection setting.
        /// </summary>
        public static string Settings_Opts_MPD_Description {
            get {
                return ResourceManager.GetString("Settings_Opts_MPD_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect.
        /// </summary>
        public static string Settings_Opts_MPD_Reconnect {
            get {
                return ResourceManager.GetString("Settings_Opts_MPD_Reconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember this.
        /// </summary>
        public static string Settings_Opts_MPD_RememberThis {
            get {
                return ResourceManager.GetString("Settings_Opts_MPD_RememberThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPD Database.
        /// </summary>
        public static string Settings_Opts_MPDDatabase {
            get {
                return ResourceManager.GetString("Settings_Opts_MPDDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Settings_Opts_Options {
            get {
                return ResourceManager.GetString("Settings_Opts_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A few preferences.
        /// </summary>
        public static string Settings_Opts_Options_Description {
            get {
                return ResourceManager.GetString("Settings_Opts_Options_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save log file (MPDCtrl__errors.txt) to desktop when an unexpected error occured..
        /// </summary>
        public static string Settings_Opts_SaveLog {
            get {
                return ResourceManager.GetString("Settings_Opts_SaveLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable debug widow..
        /// </summary>
        public static string Settings_Opts_ShowDebugWidow {
            get {
                return ResourceManager.GetString("Settings_Opts_ShowDebugWidow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        public static string Settings_Opts_Themes {
            get {
                return ResourceManager.GetString("Settings_Opts_Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Settings_Opts_Themes_Dark {
            get {
                return ResourceManager.GetString("Settings_Opts_Themes_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the current app theme.
        /// </summary>
        public static string Settings_Opts_Themes_Description {
            get {
                return ResourceManager.GetString("Settings_Opts_Themes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Settings_Opts_Themes_Light {
            get {
                return ResourceManager.GetString("Settings_Opts_Themes_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string Settings_Opts_Themes_System {
            get {
                return ResourceManager.GetString("Settings_Opts_Themes_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update MPD database on startup. (It may take a while to update).
        /// </summary>
        public static string Settings_Opts_UpdateDatabaseOnStartup {
            get {
                return ResourceManager.GetString("Settings_Opts_UpdateDatabaseOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &quot;readpicture&quot; command instead of &quot;albumart&quot;. (applicable when MPD protocol version is 0.22.0 or up).
        /// </summary>
        public static string Settings_Opts_UseReadPicture {
            get {
                return ResourceManager.GetString("Settings_Opts_UseReadPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        public static string Settings_PageTitle {
            get {
                return ResourceManager.GetString("Settings_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile deleted.
        /// </summary>
        public static string Settings_ProfileDeleted {
            get {
                return ResourceManager.GetString("Settings_ProfileDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile saved..
        /// </summary>
        public static string Settings_ProfileSaved {
            get {
                return ResourceManager.GetString("Settings_ProfileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile updated..
        /// </summary>
        public static string Settings_ProfileUpdated {
            get {
                return ResourceManager.GetString("Settings_ProfileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project info.
        /// </summary>
        public static string Settings_ProjectPage {
            get {
                return ResourceManager.GetString("Settings_ProjectPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project is hosted at GitHub as a open source project..
        /// </summary>
        public static string Settings_ProjectPage_Description {
            get {
                return ResourceManager.GetString("Settings_ProjectPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings (Ctrl+S).
        /// </summary>
        public static string Settings_ToolTip {
            get {
                return ResourceManager.GetString("Settings_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock and change password.
        /// </summary>
        public static string Settings_UnlockAndChangePassword {
            get {
                return ResourceManager.GetString("Settings_UnlockAndChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (not used).
        /// </summary>
        public static string SongFilesItemContextMenu_Add {
            get {
                return ResourceManager.GetString("SongFilesItemContextMenu_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string SongFilesListviewColumnHeader_File {
            get {
                return ResourceManager.GetString("SongFilesListviewColumnHeader_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string SongFilesListviewColumnHeader_Path {
            get {
                return ResourceManager.GetString("SongFilesListviewColumnHeader_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Queue.
        /// </summary>
        public static string SongsItemContextMenu_Add {
            get {
                return ResourceManager.GetString("SongsItemContextMenu_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MPD protocol version {0} is old. Some of the functionalities may not work properly..
        /// </summary>
        public static string StatusBarMsg_MPDVersionIsOld {
            get {
                return ResourceManager.GetString("StatusBarMsg_MPDVersionIsOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating database....
        /// </summary>
        public static string StatusMsg_UpdatingDb {
            get {
                return ResourceManager.GetString("StatusMsg_UpdatingDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
